// THIS FILE IS AUTO-GENERATED BY scripts/generate-components-map.js
// DO NOT EDIT MANUALLY

import React from 'react';

import HeroSectionOne from './blocks/hero-section/one';
import HeroSectionTwo from './blocks/hero-section/two';
import NotificationBarsFour from './blocks/notification-bars/four';
import NotificationBarsOne from './blocks/notification-bars/one';
import NotificationBarsThree from './blocks/notification-bars/three';
import NotificationBarsTwo from './blocks/notification-bars/two';

export const componentsMap: Record<string, Record<string, React.ComponentType<any>>> = {
  'hero-section': {
    'one': HeroSectionOne,
    'two': HeroSectionTwo,
  },
  'notification-bars': {
    'four': NotificationBarsFour,
    'one': NotificationBarsOne,
    'three': NotificationBarsThree,
    'two': NotificationBarsTwo,
  },
};
